### ISSUE TITLE
idea 

### ISSUE THREAD

**Issue by joeblew99** [utamaro/rsraid#2]
awesome to see a go based one.

in minio they have a golang binding based one
https://github.com/mattf/minio/tree/master/erasure

its this ay because they are tapping into the intel api to accelerate it.

I just wanted to let you know, just in case

**Comment by utamaro** [comment]
good to know,
but sorry, I don't have enough knowledge about intel cpu :(

**Comment by utamaro** [comment]
> there are many read solomon libs in golang already you can use.

yeah!

I think the fastest lib for reed solomon is:
https://github.com/klauspost/reedsolomon

>speeds exceeding 1GB/s/cpu

extremely fast!
